### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [rdbv/arpilnik#1]
cool project, but why dont you just use Keystone assembler (https://github.com/keystone-engine/keystone) to avoid messing up with code generation? You can easily support other non-X86 architectures, too.

keep it up, cheers.

**Comment by rdbv** [comment]
Yep, you're right, i should use some lib for easier code generation, but is 4fun project, and i wanted to play (and learn) with x86_64 encoding. Anyway i probably will use some lib for assembling (maybe Keystone), but later. And BTW Unicorn is srsly awesome project, very useful.

**Comment by aquynh** [comment]
nice fun project, and good plan!

btw, Keystone is the one & only cross-platform assembler framework with Python binding. there is no alternative, so it will be your only choice :-)

cheers.
